import { spawn } from "child_process";
import EEGSession from "../models/eegSession.model.js";
import User from "../models/user.model.js";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

/**
 * Run Python inference for a specific user
 * Creates a new EEG session with emotion detection results
 */
async function runInferenceForUser(userId) {
  return new Promise((resolve, reject) => {
    try {
      const inferenceDir = path.join(__dirname, "..", "..", "inference");
      const py = spawn("python", ["inference.py"], {
        cwd: inferenceDir,
      });

      let output = "";
      let errorOutput = "";

      py.stdout.on("data", (data) => {
        output += data.toString();
      });

      py.stderr.on("data", (data) => {
        errorOutput += data.toString();
        console.error(`[PYTHON ERROR for user ${userId}]:`, data.toString());
      });

      py.on("close", async (code) => {
        if (code !== 0) {
          console.error(`❌ Inference failed for user ${userId}. Exit code: ${code}`);
          console.error(`Error output: ${errorOutput}`);
          return reject(new Error(`Python inference failed with code ${code}`));
        }

        try {
          // Parse JSON result from Python
          const result = JSON.parse(output);

          // Create new EEG session with inference results
          const saved = await EEGSession.create({
            userId,
            mood: result.prediction, // Negatif / Netral / Positif
            probabilities: result.probabilities,
            photoPath: null,
            note: "Auto-generated by inference service",
          });

          console.log(`✅ Inference completed for user ${userId}: ${result.prediction}`);
          resolve(saved);
        } catch (err) {
          console.error(`❌ Failed to parse Python output for user ${userId}:`, err.message);
          reject(err);
        }
      });

      py.on("error", (err) => {
        console.error(`❌ Failed to spawn Python process for user ${userId}:`, err.message);
        reject(err);
      });
    } catch (err) {
      console.error(`❌ Error in runInferenceForUser for ${userId}:`, err.message);
      reject(err);
    }
  });
}

/**
 * Run inference for all verified users
 * Called automatically every 10 seconds
 */
async function runInferenceForAllUsers() {
  try {
    // Get all verified users
    const users = await User.find({ isVerified: true });

    if (users.length === 0) {
      console.log("ℹ️ No verified users found for inference");
      return;
    }

    console.log(`🧠 Running inference for ${users.length} verified user(s)...`);

    // Run inference for each user (can be parallelized if needed)
    const promises = users.map((user) => 
      runInferenceForUser(user._id)
        .catch((err) => {
          console.error(`⚠️ Inference failed for user ${user._id}:`, err.message);
          return null; // Continue with other users even if one fails
        })
    );

    await Promise.all(promises);
    console.log(`✅ Inference cycle completed`);
  } catch (err) {
    console.error("❌ Error in runInferenceForAllUsers:", err.message);
  }
}

/**
 * Start the automatic inference service
 * Runs every 10 seconds for all verified users
 */
export function startInferenceService() {
  console.log("🚀 Starting automatic inference service (every 10 seconds)...");

  // Run immediately on startup
  runInferenceForAllUsers();

  // Then run every 10 seconds
  setInterval(() => {
    runInferenceForAllUsers();
  }, 10000); // 10 seconds
}

/**
 * Manual trigger for single user (can be called from API endpoint)
 */
export async function triggerInferenceForUser(userId) {
  try {
    const result = await runInferenceForUser(userId);
    return result;
  } catch (err) {
    throw err;
  }
}
